export const color = {
  bgApp: 'var(--bg-app)',
  bgSidebar: 'var(--bg-sidebar)',
  bgTopbar: 'var(--bg-topbar)',
  bgCard: 'var(--bg-card)',
  bgCardHover: 'var(--bg-card-hover)',
  bgChip: 'var(--bg-chip)',
  bgChipHover: 'var(--bg-chip-hover)',
  bgInput: 'var(--bg-input)',
  bgInputFocus: 'var(--bg-input-focus)',
  bgSelectedSource: 'var(--bg-selected-source)',
  bgSourcePanel: 'var(--bg-source-panel)',
  borderSidebar: 'var(--border-sidebar)',
  borderCard: 'var(--border-card)',
  borderInput: 'var(--border-input)',
  borderInputFocus: 'var(--border-input-focus)',
  borderSelected: 'var(--border-selected)',
  textPrimary: 'var(--text-primary)',
  textSecondary: 'var(--text-secondary)',
  textMuted: 'var(--text-muted)',
  gold: 'var(--gold)',
  goldDim: 'var(--text-gold-dim)',
  green: 'var(--green-dot)',
  badgeCriminalBg: 'var(--badge-criminal-bg)',
  badgeCriminalText: 'var(--badge-criminal-text)',
  badgeProceduralBg: 'var(--badge-procedural-bg)',
  badgeProceduralText: 'var(--badge-procedural-text)',
  sourceNumBg: 'var(--source-num-bg)',
  sourceNumText: 'var(--source-num-text)',
}

export const layoutStyles = {
  app: {
    minHeight: '100vh',
    background: color.bgApp,
    color: color.textPrimary,
    fontFamily: 'var(--font-body)',
    overflow: 'hidden',
  },
  shell: {
    display: 'flex',
    height: 'calc(100vh - 48px)',
    overflow: 'hidden',
    position: 'relative',
  },
  main: {
    flex: 1,
    height: 'calc(100vh - 48px)',
    background: color.bgApp,
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    minWidth: 0,
  },
  label: {
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: '0.15em',
    textTransform: 'uppercase',
    color: color.textMuted,
  },
}
